import { writeFileSync, mkdirSync } from 'fs';
import { CHAIN_ALIASES } from '../src/chain-aliases';

function normalizeKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, '');
}

interface ChainlistEntry {
  name: string;
  chainId: number;
  shortName?: string;
  nativeCurrency?: { name?: string; symbol?: string };
}

interface DefiLlamaChainEntry {
  name: string;
  gecko_id?: string;
  tvl?: number;
  tokenSymbol?: string;
  chainId?: number | null;
}

async function main() {
  console.log('Fetching chainid.network (ethereum-lists/chains)...');
  const chainlistResp = await fetch('https://chainid.network/chains.json');
  const chainlist: ChainlistEntry[] = await chainlistResp.json();
  console.log(`  Got ${chainlist.length} chain entries`);

  console.log('Fetching DefiLlama /chains...');
  const defillamaResp = await fetch('https://api.llama.fi/chains');
  const defillamaChains: DefiLlamaChainEntry[] = await defillamaResp.json();
  console.log(`  Got ${defillamaChains.length} chain entries`);

  // Build set of known DefiLlama chain names (normalized)
  const defillamaNames = new Map<string, string>();
  for (const c of defillamaChains) {
    const normalized = normalizeKey(c.name);
    if (normalized && !defillamaNames.has(normalized)) {
      defillamaNames.set(normalized, c.name);
    }
  }

  // Also index chain IDs from DefiLlama if available
  for (const c of defillamaChains) {
    if (c.chainId && c.chainId > 0) {
      defillamaNames.set(String(c.chainId), c.name);
    }
  }

  function getWords(s: string): string[] {
    return s.trim().split(/[^a-zA-Z0-9]+/).filter(Boolean).map((w) => w.toLowerCase());
  }

  function matchAgainstKnown(input: string): string | undefined {
    const key = normalizeKey(input);
    const alias = CHAIN_ALIASES[key];
    if (alias) return alias;
    return defillamaNames.get(key);
  }

  const map: Record<string, string> = {};
  const unmatched: string[] = [];

  for (const chain of chainlist) {
    const id = String(chain.chainId);
    const shortName = chain.shortName ? chain.shortName.trim() : '';
    const name = chain.name;

    // Strategy 1: Try shortName
    if (shortName) {
      const result = matchAgainstKnown(shortName);
      if (result) {
        map[id] = result;
        continue;
      }
    }

    // Strategy 2: Try full name
    const nameResult = matchAgainstKnown(name);
    if (nameResult) {
      map[id] = nameResult;
      continue;
    }

    // Strategy 3: Split name into words and try each
    const words = getWords(name);
    for (const word of words) {
      if (word.length < 2) continue;
      const alias = CHAIN_ALIASES[word];
      if (alias) {
        map[id] = alias;
        break;
      }
      const llm = defillamaNames.get(word);
      if (llm) {
        map[id] = llm;
        break;
      }
    }
    if (map[id]) continue;

    unmatched.push(`${id}: ${name} (${shortName || '-'})`);
  }

  // Also add known chains from CHAIN_ALIASES values that we know exist on DefiLlama
  // but might not have been covered by chainid.network (non-EVM chains)
  // Already handled: these chains won't have chain IDs, so they won't be in the map anyway

  const outputPath = 'src/generated/chain-ids.ts';
  mkdirSync('src/generated', { recursive: true });
  writeFileSync(
    outputPath,
    `// Auto-generated by scripts/build-chain-id-map.ts — do not edit manually
// Sources: chainid.network/chains.json (ethereum-lists/chains) + DefiLlama /chains

export const CHAIN_ID_MAP: Record<string, string> = ${JSON.stringify(map, null, 2)};
`,
  );

  console.log(`\nGenerated ${outputPath}`);
  console.log(`  ${Object.keys(map).length} chain IDs mapped`);
  console.log(`  ${unmatched.length} chains could not be matched`);
  if (unmatched.length > 0) {
    console.log('\nUnmatched chains (sample up to 10):');
    for (const u of unmatched.slice(0, 10)) {
      console.log(`  - ${u}`);
    }
  }
}

main().catch((err) => {
  console.error('Failed to build chain ID map:', err);
  process.exit(1);
});
